### ISSUE TITLE
Add image, hover and click on hex ? 

### ISSUE THREAD

**Issue by EmilyenL** [flauwekeul/honeycomb#38]
Hello, I don't know if this place is the good one to ask that if not, please forgive me. :)
I didn't see any possibilities to add an image on a hex of the grid nor add it hover and click fonctionnalities. Is it possible ?

**Comment by flauwekeul** [comment]
Hi, this is a good place to _start_ asking questions at least 😉 

Honeycomb isn't concerned with what your grid/hexes look like. It's entirely up to you how you render a grid on the screen. Therefore, honeycomb doesn't supply any methods to render grids, you'll have to do that yourself.

For hover and click functionalities, I've made an [example before](https://jsfiddle.net/Flauwekeul/3bd6sa9r/). Rendering an image in a hex strongly depends on how you render hexes.

I can help you with honeycomb related questions, but since rendering is outside honeycomb's scope I suggest you ask rendering-related questions on places like [stackoverflow.com](//stackoverflow.com).

**Comment by EmilyenL** [comment]
Thanks for your answer I'll check that! :)

**Comment by shmup** [comment]
@flauwekeul This is a really useful example, and there's something funky with newer versions of SVG that doesn't grab the correct hex from the passed in coordinates (in the event listener). In the demo's case it is always the top left. Will update my comment when I see why this is
