### ISSUE TITLE
Grid.get doesn't work inside class

### ISSUE THREAD

**Issue by IRKhabibullin** [flauwekeul/honeycomb#40]
Hi! In my project i use svg.js along with this lib. I define class, inside which i use grid. When i call grid.get from class functions, a "TypeError: Grid.get is not a function" comes out. Grid.get works only inside class constructor. Any other class function gives error. Other Grid functions like hexesBetween also doesn't work.
Here is the [fiddle](https://jsfiddle.net/ejuq9szL/1/). Here I set click handler to polygons. Click and see an error.

**Comment by IRKhabibullin** [comment]
I've looked through closed issues (didn't notice them at start)
Looks like the guy from this [issue](https://github.com/flauwekeul/honeycomb/issues/2#issue-228970029) faces similar problem.
Grid.rectangle returns array of hexes, so array doesn't have methods, listed in docs about Grid. So is there any way to call hexesBetween method then?

You said there that you will think about using grid instance as a place to manage hexes (Like finding distance between them and so on). Didn't you come up with something about it?)

**Comment by flauwekeul** [comment]
Hi, I'm at a conference this week. I'll try to get back to your question within a week.

**Comment by flauwekeul** [comment]
I've made a new [fiddle](https://jsfiddle.net/Flauwekeul/d2Lynrxg/) that works.

You used `get()` as a static method, which doesn't exist. There is a grid `get()` instance method that works. So I've assigned the result of `Grid.rectangle()` to the `grid` property in the class and called `get()` on that.

In `onClickHandler()` you then need to reference `this.grid`, so the callback passed to `on()` should be wrapped in an arrow function.

The issue you mention is pretty old and a lot has changed since then. Please refer to the [current docs](https://github.com/flauwekeul/honeycomb#api) to see the latest API.

Let me know if you have any more questions!

**Comment by IRKhabibullin** [comment]
Yeah, thanks, indeed I used it as a static method.Sorry for bothering
