### ISSUE TITLE
how to develop hexagon grid in java script

### ISSUE THREAD

**Issue by vidyamurty** [flauwekeul/honeycomb#9]
i want to develop hexagon grid. when i click create grid button then they will be ask rows and columns after that hexagons will be displayed. how is it possible

**Comment by flauwekeul** [comment]
Have you [seen this article](https://medium.com/@Flauwekeul/honeycomb-hexagon-grids-in-javascript-555d2f9ac54f) and the included examples? Your issue seems to be related to implementing honeycomb, not with the library itself...

Maybe the folks on [stackoverflow.com](https://stackoverflow.com/) can help you out with this problem... Good luck.
